added optional-commands in plymouth-theme-ubuntu-bgrt.postinst and plymouth-theme-ubuntu-bgrt.postrm

diff --git a/debian/plymouth-theme-ubuntu-bgrt.postinst b/debian/plymouth-theme-ubuntu-bgrt.postinst
--- a/debian/plymouth-theme-ubuntu-bgrt.postinst
+++ b/debian/plymouth-theme-ubuntu-bgrt.postinst
@@ -16,6 +16,13 @@ case "$1" in
             --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                 /usr/share/plymouth/themes/ubuntu-bgrt/ubuntu-bgrt.plymouth 200 || error "Failed to update-alternatives"
 
+        if [ -f /usr/share/plymouth/ubuntu-logo.png ]; then
+            mv /usr/share/plymouth/ubuntu-logo.png /usr/share/plymouth/ubuntu-logo.png.bak || error "Failed to create ubuntu-logo backup"
+            ln -s /usr/share/plymouth/themes/ubuntu-bgrt/watermark.png /usr/share/plymouth/ubuntu-logo.png || error "Failed to create symlink to watermark.png"
+        else
+            ln -s /usr/share/plymouth/themes/ubuntu-bgrt/watermark.png /usr/share/plymouth/ubuntu-logo.png || error "Failed to create symlink to watermark.png"
+        fi       
+        
         if which update-initramfs >/dev/null 2>&1; then
             update-initramfs -u || error "Failed to update-initramfs"
         fi
diff --git a/debian/plymouth-theme-ubuntu-bgrt.postrm b/debian/plymouth-theme-ubuntu-bgrt.postrm
--- a/debian/plymouth-theme-ubuntu-bgrt.postrm
+++ b/debian/plymouth-theme-ubuntu-bgrt.postrm
@@ -16,6 +16,11 @@ case "$1" in
             --remove default.plymouth \
                 /usr/share/plymouth/themes/ubuntu-bgrt/ubuntu-bgrt.plymouth || error "Failed to update-alternatives"
 
+        if [ -f /usr/share/plymouth/ubuntu-logo.png.bak ]; then
+            rm /usr/share/plymouth/ubuntu-logo.png || error "Failed to remove symlink ubuntu-logo.png to watermark.png"
+            mv /usr/share/plymouth/ubuntu-logo.png.bak /usr/share/plymouth/ubuntu-logo.png || error "Failed to reset to ubuntu-logo.png"
+        fi
+        
         if which update-initramfs >/dev/null 2>&1; then
             update-initramfs -u || error "Failed to update-initramfs"
         fi
